exclude: 'node_modules|.git'
default_stages: [commit]
fail_fast: false


repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: trailing-whitespace
        files: "selling_management.*"
        exclude: ".*json$|.*txt$|.*csv|.*md"
      - id: check-yaml
      - id: no-commit-to-branch
      - id: check-merge-conflict
      - id: check-ast

  - repo: https://github.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        additional_dependencies: [
          'flake8-bugbear',
        ]
        args: ['--config', '.flake8']
        exclude: ".*setup.py$"

  - repo: https://github.com/timothycrosley/isort
    rev: 5.9.1
    hooks:
      - id: isort
        exclude: ".*setup.py$"

ci:
    autoupdate_schedule: weekly
    skip: []
    submodules: false